# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personalization-02-security.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 503)
        self.TitleLabel = QtWidgets.QLabel(Dialog)
        self.TitleLabel.setGeometry(QtCore.QRect(20, 20, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.IntroLabel = QtWidgets.QLabel(Dialog)
        self.IntroLabel.setGeometry(QtCore.QRect(10, 60, 351, 61))
        self.IntroLabel.setWordWrap(True)
        self.IntroLabel.setObjectName("IntroLabel")
        self.HardenedButton = QtWidgets.QRadioButton(Dialog)
        self.HardenedButton.setGeometry(QtCore.QRect(20, 110, 81, 21))
        self.HardenedButton.setChecked(True)
        self.HardenedButton.setObjectName("HardenedButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.HardenedButton)
        self.HardenedButton_2 = QtWidgets.QRadioButton(Dialog)
        self.HardenedButton_2.setGeometry(QtCore.QRect(20, 210, 81, 21))
        self.HardenedButton_2.setObjectName("HardenedButton_2")
        self.buttonGroup.addButton(self.HardenedButton_2)
        self.IntroLabel_2 = QtWidgets.QLabel(Dialog)
        self.IntroLabel_2.setGeometry(QtCore.QRect(50, 140, 351, 61))
        self.IntroLabel_2.setWordWrap(True)
        self.IntroLabel_2.setObjectName("IntroLabel_2")
        self.IntroLabel_3 = QtWidgets.QLabel(Dialog)
        self.IntroLabel_3.setGeometry(QtCore.QRect(50, 230, 351, 61))
        self.IntroLabel_3.setWordWrap(True)
        self.IntroLabel_3.setObjectName("IntroLabel_3")
        self.CancelButton = QtWidgets.QPushButton(Dialog)
        self.CancelButton.setGeometry(QtCore.QRect(10, 470, 75, 25))
        self.CancelButton.setObjectName("CancelButton")
        self.NextButton = QtWidgets.QPushButton(Dialog)
        self.NextButton.setGeometry(QtCore.QRect(310, 470, 75, 25))
        self.NextButton.setObjectName("NextButton")
        self.IntroLabel_4 = QtWidgets.QLabel(Dialog)
        self.IntroLabel_4.setGeometry(QtCore.QRect(10, 300, 351, 61))
        self.IntroLabel_4.setWordWrap(True)
        self.IntroLabel_4.setObjectName("IntroLabel_4")
        self.IntroLabel_5 = QtWidgets.QLabel(Dialog)
        self.IntroLabel_5.setGeometry(QtCore.QRect(20, 380, 161, 31))
        self.IntroLabel_5.setWordWrap(True)
        self.IntroLabel_5.setObjectName("IntroLabel_5")
        self.pin1 = QtWidgets.QLineEdit(Dialog)
        self.pin1.setGeometry(QtCore.QRect(210, 380, 161, 21))
        self.pin1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin1.setObjectName("pin1")
        self.pin2 = QtWidgets.QLineEdit(Dialog)
        self.pin2.setGeometry(QtCore.QRect(210, 420, 161, 21))
        self.pin2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pin2.setObjectName("pin2")
        self.IntroLabel_6 = QtWidgets.QLabel(Dialog)
        self.IntroLabel_6.setGeometry(QtCore.QRect(20, 420, 171, 31))
        self.IntroLabel_6.setWordWrap(True)
        self.IntroLabel_6.setObjectName("IntroLabel_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BTChip setup - security"))
        self.TitleLabel.setText(_translate("Dialog", "BTChip setup - security (2/3)"))
        self.IntroLabel.setText(_translate("Dialog", "Please choose a security profile"))
        self.HardenedButton.setText(_translate("Dialog", "Hardened"))
        self.HardenedButton_2.setText(_translate("Dialog", "PIN only"))
        self.IntroLabel_2.setText(_translate("Dialog", "You need to remove the dongle and insert it again to get a second factor validation of all operations. Recommended for expert users and to be fully protected against malwares."))
        self.IntroLabel_3.setText(_translate("Dialog", "You only need to enter a PIN once when inserting the dongle. Transactions are not protected against malwares"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.NextButton.setText(_translate("Dialog", "Next"))
        self.IntroLabel_4.setText(_translate("Dialog", "Please choose a PIN associated to the BTChip dongle. The PIN protects the dongle in case it is stolen, and can be up to 32 characters. The dongle is wiped  if a wrong PIN is entered 3 times in a row."))
        self.IntroLabel_5.setText(_translate("Dialog", "Enter the new PIN : "))
        self.IntroLabel_6.setText(_translate("Dialog", "Repeat the new PIN :"))

